title: Zhonghui Li's Homepage
page-top-title: ZHonghui Li
top-section-bg-text: Anhui University
home-subtitle: Zhonghui Li&ensp;|&ensp;李忠辉
copyright-text: '&copy; Sen Li 2023-2024. All Rights Reserved.'
